const actionTypes = {
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  SET_INGREDIENTS: "SET_INGREDIENTS",
  FETCH_INGREDIENTS_FAILED: "FETCH_INGREDIENTS_FAILED",
  PURCHASE_BURGER_SUCCESSED: "PURCHASE_BURGER_SUCCESSED",
  PURCHASE_BURGER_FAILED: "PURCHASE_BURGER_FAILED",
  PURCHASE_BURGER_STARTED: "PURCHASE_BURGER_STARTED",
  INIT_PURCHASE: "INIT_PURCHASE",
};

export default actionTypes;
