const actionTypes = {
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  SET_INGREDIENTS: "SET_INGREDIENTS",
  FETCH_INGREDIENTS_FAILED: "FETCH_INGREDIENTS_FAILED",

  PURCHASE_BURGER_SUCCEEDED: "PURCHASE_BURGER_SUCEEDED",
  PURCHASE_BURGER_FAILED: "PURCHASE_BURGER_FAILED",
  PURCHASE_BURGER_STARTED: "PURCHASE_BURGER_STARTED",
  INIT_PURCHASE: "INIT_PURCHASE",
  FETCH_ORDERS_SUCCEEDED: "FETCH_ORDERS_SUCCEEDED",
  FETCH_ORDERS_FAILED: "FETCH_ORDERS_FAILED",
  FETCH_ORDERS_STARTED: "FETCH_ORDERS_STARTED",

  AUTH_SUCCESS: "AUTH_SUCCESS",
  AUTH_FAIL: "AUTH_FAIL",
  AUTH_START: "AUTH_START",
};

export default actionTypes;
