const actionType = {
  ADD_INGREDIENT: "ADD_INGREDIENT",
  REMOVE_INGREDIENT: "REMOVE_INGREDIENT",
  ADD_TOTAL_PRICE: "ADD_TOTAL_PRICE",
  SUBSTRACT_TOTAL_PRICE: "SUBSTRACT_TOTAL_PRICE",
};

export default actionType;
